Repository elastic/mito, pull requests merged in 2024-04, with the labels that each got.

#57 mod: update past vulnerable versions of dependencies
  go.mod
  go.sum
Labels: enhancement, Team:Security-External Integrations

#59 lib/collections.go - fix with_{replace,update} doc
  lib/collections.go
Labels: documentation

#51 Add a -max_executions flag and config option to limit evaluations
  mito.go
  testdata/want_more_max.txt
Labels: Team:Security-External Integrations
